%CompositeModule PyQt4.Qt

%Include QtCore/QtCoremod.sip
%Include QtGui/QtGuimod.sip
%Include QtHelp/QtHelpmod.sip
%Include QtNetwork/QtNetworkmod.sip
%Include QtDBus/QtDBusmod.sip
%Include QtDeclarative/QtDeclarativemod.sip
%Include QtScript/QtScriptmod.sip
%Include QtScriptTools/QtScriptToolsmod.sip
%Include QtXml/QtXmlmod.sip
%Include QtSql/QtSqlmod.sip
%Include QtSvg/QtSvgmod.sip
%Include QtTest/QtTestmod.sip
%Include QtXmlPatterns/QtXmlPatternsmod.sip
%Include QtDesigner/QtDesignermod.sip
